services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: ReportProduceDB
    restart: unless-stopped
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1a2b3c4r#$"

  reportproducer:
    image: ${DOCKER_REGISTRY-}reportproducer
    build:
      context: .
      dockerfile: ReportProducer/Dockerfile
    depends_on:
      - sqlserver
